import type { Renderer } from './types.js';
import { heading, table, bulletList, yamlFrontmatter } from '../utils/markdown.js';

export const agentsMdRenderer: Renderer = {
  outputPath: 'AGENTS.md',

  render(ctx) {
    const lines: string[] = [];

    lines.push(yamlFrontmatter({
      generated_by: 'ctxify',
      version: ctx.metadata.ctxifyVersion,
      last_scanned: ctx.metadata.generatedAt,
    }));
    lines.push('');

    lines.push(heading(1, 'Workspace Context'));
    lines.push('');
    lines.push(`> Auto-generated by ctxify. Read this file first for workspace orientation.`);
    lines.push('');

    // Repos table
    lines.push(heading(2, 'Repositories'));
    lines.push('');
    if (ctx.repos.length > 0) {
      lines.push(table(
        ['Name', 'Language', 'Framework', 'Description'],
        ctx.repos.map((r) => [
          r.name,
          r.language || '—',
          r.framework || '—',
          r.description || '—',
        ]),
      ));
    } else {
      lines.push('No repositories detected.');
    }
    lines.push('');

    // Key relationships
    if (ctx.relationships.length > 0) {
      lines.push(heading(2, 'Key Relationships'));
      lines.push('');
      const highConfidence = ctx.relationships.filter((r) => r.confidence >= 0.7);
      if (highConfidence.length > 0) {
        lines.push(bulletList(
          highConfidence.map((r) => `**${r.from}** → **${r.to}** (${r.type}): ${r.evidence}`),
        ));
      }
      lines.push('');
    }

    // Satellite files index
    lines.push(heading(2, 'Context Files'));
    lines.push('');
    const satellites = [
      ['.ctx/topology.yaml', 'Machine-readable repo graph with dependencies'],
      ['.ctx/api-contracts.md', 'API endpoint signatures across all repos'],
      ['.ctx/shared-types.md', 'Types/interfaces crossing repo boundaries'],
      ['.ctx/env-vars.md', 'Environment variable names (never values) across repos'],
      ['.ctx/db-schema.md', 'Database models and relationships'],
    ];

    // Add per-repo summaries
    for (const repo of ctx.repos) {
      satellites.push([`.ctx/repo-${repo.name}.md`, `${repo.name}: structure, patterns, key files`]);
    }

    if (ctx.questions.length > 0) {
      satellites.push(['.ctx/questions.md', `${ctx.questions.length} ambiguities need clarification`]);
    }

    lines.push(table(['File', 'Contents'], satellites));
    lines.push('');

    // Quick stats
    lines.push(heading(2, 'Quick Stats'));
    lines.push('');
    lines.push(bulletList([
      `${ctx.repos.length} repositories`,
      `${ctx.apiEndpoints.length} API endpoints`,
      `${ctx.sharedTypes.length} shared types`,
      `${ctx.envVars.length} environment variables`,
      `${ctx.relationships.length} relationships`,
      `${ctx.conventions.length} conventions detected`,
    ]));
    lines.push('');

    return lines.join('\n');
  },
};
